/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cross.platform.test.suite;

public class App {
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    @Deprecated
    public String getGreeting() {
        return "Hello World!";
    }
}
