/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cross.platform.test.suite.test;

import cross.platform.test.suite.configuration.manager.DriverManager;
import cross.platform.test.suite.configuration.manager.ReportManager;
import cross.platform.test.suite.properties.MobileConfig;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.testng.annotations.Guice;
import org.testng.annotations.Test;

import javax.inject.Inject;

@Slf4j
@Guice
@Test
@Getter
@RequiredArgsConstructor(onConstructor = @__(@Inject))
public class AppTest extends BaseSetupTest implements ReportTest {

    private final MobileConfig mobileConfig;
    private final ReportManager reportManager;
    private final DriverManager driverManager;
    
    @Test(description = "appTest method description.")
    public void appTest() {
        log.info(this.driverManager.getDriver().getRemoteAddress().toString());
    }
    
}
