version: "3"
services:
  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:latest
    ports:
      - "4442-4444:4442-4444"

  node-1:
    image: selenium/node-docker:latest
    depends_on:
      - selenium-hub
    volumes:
      - ./node-android-4723.toml:/opt/bin/config.toml
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    extra_hosts:
      - "host.docker.internal:host-gateway"

  node-2:
    image: selenium/node-docker:latest
    depends_on:
      - selenium-hub
    volumes:
      - ./node-android-4724.toml:/opt/bin/config.toml
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    extra_hosts:
      - "host.docker.internal:host-gateway"
