/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cross.platform.test.suite.test.apptest;

import cross.platform.test.suite.configuration.manager.DriverManager;
import cross.platform.test.suite.properties.MobileConfig;
import cross.platform.test.suite.test.common.AbstractSetupTest;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.testng.annotations.Guice;

import javax.inject.Inject;

@Slf4j
@Guice
@Getter
@RequiredArgsConstructor(onConstructor = @__(@Inject))
public class AppSetupTest extends AbstractSetupTest {

    private final MobileConfig mobileConfig;
    private final DriverManager driverManager;
}
